data:extend(
{
  {
    type = "recipe",
    name = "smelt-recyclate-to-iron",
    enabled = true,
    ingredients = {{"iron-recyclate", 1}},
    result = "iron-plate",
    category = "smelting",
    energy_required = 3 /1.5,
	allow_as_intermediate = false,
    hidden = true,
  },
  {
    type = "recipe",
    name = "smelt-recyclate-to-copper",
    enabled = true,
    ingredients = {{"copper-recyclate", 1}},
    result = "copper-plate",
    category = "smelting",
    energy_required = 3 /1.5,
	allow_as_intermediate = false,
    hidden = true,
  },
  {
    type = "recipe",
    name = "smelt-recyclate-to-steel",
    enabled = true,
    ingredients = {{"steel-recyclate", 1}},
    result = "steel-plate",
    category = "smelting",
    energy_required = 17.5 /1.5,
	allow_as_intermediate = false,
    hidden = true,
  },
  {
    type = "recipe",
    name = "smelt-recyclate-to-plastic",
    enabled = true,
    ingredients = {{"plastic-recyclate", 1}},
    result = "plastic-bar",
    category = "smelting",
    energy_required = 2 /1.5,
	allow_as_intermediate = false,
    hidden = true,
  },
}
)